services:



  postgres:
    image: postgres:15
    container_name: fraud-postgres
    environment:
      POSTGRES_DB: fraud_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: fraud-redis
    ports:
      - '6379:6379'

  kafka:
    image: 'apache/kafka:latest'
    container_name: fraud-kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Regisztráljuk a belső (9092), a kontroller (9093) és a külső (29092) csatornákat
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092

      # Összekötjük őket a biztonsági protokollal
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      # FONTOS JAVÍTÁS 🎯:
      # - A 9092-es porton a Docker belső hálózatát hirdeti (fraud-kafka:9092)
      # - A 29092-es porton pedig a te Mac-edet hirdeti (localhost:29092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fraud-kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: fraud-opensearch
    environment:
      - cluster.name=fraud-cluster
      - node.name=fraud-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true # Kikapcsolja a demo SSL-t a könnyebb lokális fejlesztésért
      - DISABLE_SECURITY_PLUGIN=true     # Lokálisan HTTP-n fogunk kommunikálni HTTPS helyett
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: fraud-dashboards
    ports:
       - "5601:5601"
    environment:
       - OPENSEARCH_HOSTS=["http://opensearch:9200"]
       - DISABLE_SECURITY_PLUGIN=true
    depends_on:
      - opensearch

volumes:
  opensearch-data: {}