services:
  postgres:
    image: postgres:15
    container_name: fraud-postgres
    environment:
      POSTGRES_DB: fraud_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: fraud-redis
    ports:
      - '6379:6379'

  kafka:
    image: 'apache/kafka:latest'
    container_name: fraud-kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fraud-detection-service-kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@fraud-detection-service-kafka-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #For deleting every message we can use
      #KAFKA_LOG_RETENTION_HOURS: 1
      #And
      #KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000