app:
  kafka:
    topic: transactions
    consumer-group: "fraud-group"
    partitions: 3 # just for fun
    scheduling:
      enabled: true

                ### TELJESÍTMÉNYMÉRÉSI EREDMÉNYEK (BENCHMARKS) ###
      # -----------------------------------------------------------------------
      # Adatmennyiség | Konfiguráció          | Idő (ms)   | Idő (perc/mp)
      # -----------------------------------------------------------------------
      # 10 000 rekord | 1 szál / 3 partíció   | 129 095 ms | ~2 perc 09 mp
      # 10 000 rekord | 3 szál / 3 partíció   | 127 590 ms | ~2 perc 07 mp
      # 10 000 rekord | 6 szál / 6 partíció   | 149 408 ms | ~2 perc 29 mp
      # -----------------------------------------------------------------------
      # 50 000 rekord | 1 szál / 3 partíció   | 675 994 ms | ~11 perc 15 mp
      # 50 000 rekord | 3 szál / 3 partíció   | 654 510 ms | ~10 perc 54 mp
      # 50 000 rekord | 6 szál / 6 partíció   | 663 876 ms | ~11 perc 03 mp
      # -----------------------------------------------------------------------
      # Megfigyelések:
      # - 10k-nál a 6 szál lassabb (overhead), itt a 3 szál az optimális.
      # - 50k-nál a 3 szál hozta a legjobb eredményt.
      # - A localhost/DB szűk keresztmetszet miatt a szálak száma nem skálázódik lineárisan.


spring:
  # 1. Block Docker Compose Lifecycle Manager
  docker:
    compose:
      enabled: false

  # 2. Postgres setup
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # 3. Redis setup
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Kafka setup
  kafka:
    bootstrap-servers: localhost:29092

    listener:
      # 10000ms = After 10 sec sends Idle event
      idle-event-interval: 10000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "hu.zoltanb.projects.fraud.model.Transaction"

fraud:
  detection:
    card-test:
      amount-limit: 4000
      count-limit: 4
      duration-minutes: 2
    velocity:
      count-limit: 10
      duration-minutes: 2
  generator:
    transaction-count: 10000
    initial-delay: 3000
    min-user-id: 100
    max-user-id: 1000
    min-merchant-id: 100
    max-merchant-id: 110
    min-amount: 50
    max-amount: 10001
    sleep-ms: 10