app:
  kafka:
    topic: transactions
    consumer-group: "fraud-group"
    partitions: 3 # just for fun
    scheduling:
      enabled: true

                ### BENCHMARKS ###
      # -----------------------------------------------------------------------
      # Data | configuration          | Time (ms)   | Time (perc/mp)
      # -----------------------------------------------------------------------
      # 10 000 record | 1 thread / 3 partitions   | 129 095 ms | ~2 min 09 mp
      # 10 000 record | 3 thread / 3 partitions   | 127 590 ms | ~2 min 07 mp
      # 10 000 record | 6 thread / 6 partitions   | 149 408 ms | ~2 min 29 mp
      # -----------------------------------------------------------------------
      # 50 000 record | 1 thread / 3 partitions   | 675 994 ms | ~11 min 15 mp
      # 50 000 record | 3 thread / 3 partitions   | 654 510 ms | ~10 min 54 mp
      # 50 000 record | 6 thread / 6 partitions   | 663 876 ms | ~11 min 03 mp
      # -----------------------------------------------------------------------
      # Result:
      # - Localhost and DB are the bottlenecks
      # Record number = row number in DB!!!
      # - After using batch saving:
      # 100 000 record | 3 thread / 3 partitions in 73 316 ms/ ~1 min 13 mp!!!
      # 1 000 000 record | 3 thread / 3 partitions in 646 923 ms/ ~10 min 47 mp!!!

spring:
  # 1. Block Docker Compose Lifecycle Manager
  docker:
    compose:
      enabled: false

  # 2. Postgres setup
  datasource:
    hikari:
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/fraud_db?reWriteBatchedInserts=true
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      jdbc.batch_size: 500
      order_inserts: true
      order_updates: true
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # 3. Redis setup
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Kafka setup
  kafka:
    bootstrap-servers: localhost:29092

    listener:
      # 10000ms = After 10 sec sends Idle event
      type: batch
      ack-mode: manual
      idle-event-interval: 5000ms
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      consumer-group: fraud-detection-group
      auto-offset-reset: earliest
      fetch-min-bytes: 1024
      fetch-max-wait: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "hu.zoltanb.projects.fraud.model.Transaction"

fraud:
  detection:
    card-test:
      amount-limit: 500
      count-limit: 4
      duration-minutes: 2
    velocity:
      count-limit: 20
      duration-minutes: 1
  generator:
    transaction-count: 100000
    initial-delay: 3000
    min-user-id: 100
    max-user-id: 800
    min-merchant-id: 100
    max-merchant-id: 110
    min-amount: 50
    max-amount: 10000
    sleep-ms: 10






