apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    password: password
    database: fraud_db
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      database: fraud_db
    secureJsonData:
      password: password