spring:
  # 1. Block Docker Compose Lifecycle Manager
  docker:
    compose:
      enabled: false

  # 2. Postgres setup
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # 3. Redis setup
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Kafka setup (using 29092 as outsider port)
  kafka:
    bootstrap-servers: localhost:29092

    listener:
      # 10000ms = After 10 sec sends Idle event
      idle-event-interval: 10000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: fraud-group-clean-start
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "hu.zoltanb.projects.fraud.model.Transaction"

fraud:
  detection:
    card-test:
      amount-limit: 2000
      count-limit: 4
      duration-minutes: 10
    velocity:
      count-limit: 15
      duration-minutes: 1
  generator:
    transaction-count: 10000
    initial-delay-ms: 3000
    min-user-id: 100
    max-user-id: 500
    min-merchant-id: 100
    max-merchant-id: 110
    min-amount: 50
    max-amount: 10001
    sleep-ms: 10