DROP TABLE IF EXISTS transactions;

CREATE TABLE transactions
(
    -- GENERATED BY DEFAULT AS IDENTITY
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT NOT NULL,
    fraud_types text[]
);